DROP TABLE IF EXISTS experiments CASCADE;
DROP TABLE IF EXISTS trials CASCADE;
DROP TABLE IF EXISTS results CASCADE;
DROP TABLE IF EXISTS cadvisor CASCADE;
DROP TABLE IF EXISTS operator_metrics CASCADE;
DROP TABLE IF EXISTS plots CASCADE;
DROP TABLE IF EXISTS metric_plots CASCADE;
