---
- hosts: all
  tasks:
    - name: Pull the Damsl Docker image for Spark
      shell: docker pull damsl/spark

    - name: Cleanup existing containers for Spark
      shell: docker rm -f sparkMaster sparkWorker
      ignore_errors: yes

- hosts: master
  tasks:
    - name: Run the spark Master class inside of a Docker container
      shell: docker run --pid=host --privileged -v /tmp --net=host --name="sparkMaster" -d damsl/spark /sbin/spark_master.sh {{groups['master'][0]}}

- hosts: workers
  tasks:
    - name: Run the spark Worker class inside of a Docker container
      shell: docker run --pid=host --privileged -v /tmp:/tmp -d --net=host --name="sparkWorker" damsl/spark /sbin/spark_worker.sh {{groups['master'][0]}}
