---
- hosts: all
  tasks:
    - name: Pull the Damsl Docker image for HDFS
      shell: docker pull damsl/hdfs

    - name: Ensure remote config directory exists
      file: path={{persistent_storage_folder}}/config/ state=directory mode=774

    - name: Ensure remote directory for sockets exists
      file: path={{hadoop_sockets_folder}} state=directory mode=744 owner=root

    - name: Copy hdfs-site.xml to remote config directory
      template: src=../files/hdfs-site.xml dest={{persistent_storage_folder}}/config/

    - name: Create core-site.xml from template
      template: src=../files/core-site.xml dest={{persistent_storage_folder}}/config/
    
- hosts: namenode
  tasks:
    - name: Remove existing container for Namenode
      shell: docker rm -f HDFS_namenode
      ignore_errors: yes

    - name: Run the namenode inside of a Docker container
      shell: docker run -d --net=host -v {{persistent_storage_folder}}:/hadoop/  --name="HDFS_namenode" damsl/hdfs /sbin/namenode_startup.sh


- hosts: datanodes
  tasks:
    - name: Remove existing container for Datanode
      shell: docker rm -f HDFS_datanode
      ignore_errors: yes

    - name: Run the datanode inside of a Docker container
      shell: docker run -d --net=host -v {{persistent_storage_folder}}:/hadoop/ -v {{hadoop_sockets_folder}}:/hadoop_sockets/ --name="HDFS_datanode" damsl/hdfs /sbin/datanode_startup.sh 
