- hosts: master
  tasks:
    - name: Kill and Remove the jobmanager
      shell: docker rm -f naiad_master

- hosts: workers
  tasks:
    - name: Kill and Remove the slaves
      shell: docker rm -f naiad_slave
