- hosts: jobmanager 
  tasks: 
    - name: Kill and Remove the jobmanager
      shell: docker rm -f flink_jobmanager
      ignore_errors: yes

- hosts: slaves
  tasks:
    - name: Kill and Remove the slaves
      shell: docker rm -f flink_slave
      ignore_errors: yes
