- hosts: target_hosts
  tasks:
    - include: ../plays/deploy_k3.yml
      vars:
        app_name: amplab_q1_final
        binary: /tmp/q1
        numprocs: 16
        result_var: local_q1_results
        log_enabled: false
        k3_variables:
          x: 1000
          master: [192.168.0.40, 40000]
          role: rows
        data_files:
          - name: dataFiles
            prefix: /local/data/amplab/1024/rankings/rankings
            num: 16
