---
  - name: Setup docker
    include: setup_docker.yml

  - name: run the binary in a docker container
    shell: docker run -d --net=host --name="{{docker_image}}_40000" -v {{setup_dir}}:/app_setup -v {{data_dir}}40000:/app_data -v /local:/local {{docker_image}} run_k3 {% if (log_enabled is defined) and log_enabled %} -l /app_data {% endif %} {%- if (result_var is defined) %} -r {{result_var}} -o /app_data {%- endif %} {% for item in range(numprocs) %} -p /app_setup/run_{{40000+item}}.yml {% endfor %} 
  
  - name: Cleanup Docker
    include: cleanup_docker.yml
